name: CD-Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: Setup JDK 18
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle command - assembleDebug
        run: ./gradlew assembleDebug

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          releaseNotesFile: release/v1.0.txt
          file: app/build/outputs/apk/debug/app-debug.apk